---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin
  labels:
    app.kubernetes.io/instance: jellyfin
    app.kubernetes.io/name: jellyfin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4G
  storageClassName: shared-ssd

