---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr
  labels:
    app.kubernetes.io/instance: sonarr
    app.kubernetes.io/name: sonarr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10G
  storageClassName: shared-ssd

