# https://github.com/anchorlytics/charts/blob/main/sonarr/values.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarr-values
data:
  values.yaml: |
    volumes:
    - name: appdata
      persistentVolumeClaim:
        claimName: sonarr
    - name: usenet
      persistentVolumeClaim:
        claimName: usenet
    - name: tv
      persistentVolumeClaim:
        claimName: tv
    volumeMounts:
    - name: usenet
      mountPath: /usenet
    - name: tv
      mountPath: /tv
    ingress:
      enabled: true
      host: sonarr.home.seanho.com
      annotations:
        cert-manager.io/cluster-issuer: le-prod
        nginx.ingress.kubernetes.io/proxy-body-size: 1m
