---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vaultwarden-db
spec:
  instances: 3

  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 17

  bootstrap:
    initdb:
      database: bitnami_vaultwarden
      owner: bn_vaultwarden
      secret:
        name: vaultwarden-db-pw

  storage:
    size: 2Gi
    storageClass: local-path
