# https://github.com/gissilabs/charts/tree/master/vaultwarden
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
spec:
  interval: 10m
  chart:
    spec:
      interval: 2h
      sourceRef:
        kind: HelmRepository
        name: vaultwarden
      chart: vaultwarden
      version: "1.2.5"
  valuesFrom:
  - kind: ConfigMap
    name: helm-values
