# https://hub.docker.com/r/vaultwarden/server
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: vaultwarden
  valuesFrom:
  - kind: ConfigMap
    name: helm-values
  - kind: Secret
    name: smtp
