---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
spec:
  interval: 10m
  chartRef:
    kind: HelmRepository
    name: vaultwarden
  valuesFrom:
  - kind: ConfigMap
    name: helm-values
