---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
spec:
  chart:
    spec:
      interval: 10m
      sourceRef:
        kind: HelmRepository
        name: vaultwarden
      chart: vaultwarden
      version: "1.2.4"
  valuesFrom:
  - kind: ConfigMap
    name: helm-values
