 # https://hub.docker.com/r/vaultwarden/server
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vaultwarden
resources:
- src.yaml
- helm.yaml
- values.yaml
- secret.yaml
images:
- name: vaultwarden 
  newTag: 1.32.7
