# https://github.com/gissilabs/charts/tree/master/vaultwarden
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vaultwarden
spec:
  interval: 1d
  url: https://gissilabs.github.io/charts
