# https://lab.frogg.it/doca/vaultwarden-helm
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: vaultwarden
spec:
  interval: 10m
  url: oci://registry-1.docker.io/captnbp/vaultwarden
  ref:
    semver: "^0.1.8"
