apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-values
  namespace: vaultwarden
data:
  persistence:
    size: 10Gi
  ingress:
    enabled: true
    hostname: replace.in.overlay.local
  extraEnvVars:
  - name: USE_SENDMAIL
    value: "1"

