---
apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-values
data:
  values.yaml: |
    vaultwarden:
      allowSignups: false
      allowInvitation: false
      passwordHintsAllowed: false
      enableSends: false
      emergency:
        enabled: false
      admin:
        enabled: true
        existingSecret: vaultwarden-pw
    ingress:
      enabled: true
      host: pw.home.seanho.com
      tls:
      - secretName: vaultwarden-tls
        hosts:
        - pw.home.seanho.com
      annotations:
        cert-manager.io/cluster-issuer: le-prod
      persistence:
        enabled: true
        size: 2Gi
        storageClass: shared-ssd

