---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux
  namespace: flux-system
spec:
  url: https://github.com/anchorlytics/flux
  ref:
    branch: main
  secretRef:
    name: flux-github-auth
  interval: 5m0s
