# https://configarr.raydak.de/docs/configuration/config-file
# https://recyclarr.dev/wiki/guide-configs/
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configarr
data:
  config.yml: |
    trashGuideUrl: https://github.com/TRaSH-Guides/Guides
    recyclarrConfigUrl: https://github.com/recyclarr/config-templates

    sonarr:
      tv:
        base_url: http://sonarr:8989
        api_key: !secret SONARR_API_KEY

        quality_definition:
          type: series

        include:
        - template: sonarr-quality-definition-series

        - template: sonarr-v4-quality-profile-web-2160p
        - template: sonarr-v4-custom-formats-web-2160p

        - template: sonarr-v4-quality-profile-web-1080p
        - template: sonarr-v4-custom-formats-web-1080p

        custom_formats:
        - trash_ids:
          - 9b27ab6498ec0f31a3353992e19434ca # no DV (WEBDL)
          - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          - 06d66ab109d4d2eddb2794d21526d140 # Retags
          - 1b3994c551cbb92a2c781af061f4ab44 # Scene
          assign_scores_to:
          - name: WEB-1080p
          - name: WEB-2160p

    radarr: 
      movies:
        base_url: http://radarr:7878
        api_key: !secret RADARR_API_KEY

        quality_definition:
          type: movies

        include:
        - template: radarr-quality-definition-movie

        - template: radarr-quality-profile-remux-web-2160p
        - template: radarr-custom-formats-remux-web-2160p

        - template: radarr-quality-profile-uhd-bluray-web
        - template: radarr-custom-formats-uhd-bluray-web

        - template: radarr-quality-profile-remux-web-1080p
        - template: radarr-custom-formats-remux-web-1080p

        custom_formats:
        - trash_ids:
          - 923b6abef9b17f937fab56cfcf89e1f1 # no DV (WEBDL)
          - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          - cc444569854e9de0b084ab2b8b1532b2 # Black and White Editions
          - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
          - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
          - f537cf427b64c38c8e36298f657e4828 # Scene
          assign_scores_to:
          - name: Remux + WEB 2160p
          - name: UHD Bluray + WEB
          - name: Remux + WEB 1080p
