---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: configarr
  labels:
    app.kubernetes.io/instance: configarr
    app.kubernetes.io/name: configarr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10G
  storageClassName: shared-ssd

