# https://github.com/jellyfin/jellyfin-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  interval: 10m
  chart:
    spec:
      interval: 2h
      sourceRef:
        kind: HelmRepository
        name: jellyfin
      chart: jellyfin
      version: "2.1.0"
  valuesFrom:
  - kind: ConfigMap
    name: jellyfin-values
