---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: anchorlytics
spec:
  type: github
  events:
    - "ping"
    - "push"
  secretRef:
    name: webhook-token
  resources:
    - kind: HelmRepository
      name: anchorlytics

