# https://artifacthub.io/packages/helm/metallb/metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
spec:
  interval: 10m
  chart:
    spec:
      interval: 2h
      sourceRef:
        kind: HelmRepository
        name: metallb
      chart: metallb
      version: "0.15.3"
  valuesFrom:
  - kind: ConfigMap
    name: helm-values
