# https://github.com/bitnami/charts/blob/master/bitnami/metallb/
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-values
data:
  values.yaml: |
    prometheusRule:
      enabled: true
    controller:
      nodeSelector:
        role: ingress
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
    speaker:
      nodeSelector:
        role: ingress
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
