# https://github.com/anchorlytics/charts/tree/main/radarr
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
spec:
  interval: 1h
  chart:
    spec:
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: anchorlytics
      chart: radarr
      version: "0.1.1"
  valuesFrom:
  - kind: ConfigMap
    name: radarr-values
