---
apiVersion: v1
kind: ConfigMap
metadata:
  name: radarr-values
data:
  values.yaml: |
    image:
      tag: 5.19.3 # https://github.com/linuxserver/docker-radarr/releases
    volumes:
    - name: appdata
      persistentVolumeClaim:
        claimName: radarr
    - name: usenet
      persistentVolumeClaim:
        claimName: usenet
    - name: movies
      persistentVolumeClaim:
        claimName: movies
    volumeMounts:
    - name: usenet
      mountPath: /usenet
    - name: movies
      mountPath: /movies
    ingress:
      enabled: true
      host: radarr.home.seanho.com
      annotations:
        cert-manager.io/cluster-issuer: le-prod
        nginx.ingress.kubernetes.io/proxy-body-size: 1m
