# https://github.com/vmware-tanzu/helm-charts/tree/main/charts/velero
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
spec:
  interval: 10m
  chart:
    spec:
      interval: 2h
      sourceRef:
        kind: HelmRepository
        name: velero
      chart: velero
      version: "8.2.0"
  valuesFrom:
  - kind: ConfigMap
    name: helm-values
