# https://hub.docker.com/r/velero/velero/tags
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: velero
resources:
- src.yaml
- helm.yaml
- values.yaml
images:
- name: velero
  newTag: v1.15.1
