# https://github.com/immich-app/immich-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  interval: 10m
  chart:
    spec:
      interval: 2h
      sourceRef:
        kind: HelmRepository
        name: immich
      chart: immich
      version: "0.9.0"
  valuesFrom:
  - kind: ConfigMap
    name: helm-values
