---
apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-values
data:
  values.yaml: |
    server:
      ingress:
        main:
          enabled: true
          hosts:
          - host: photos.home.seanho.com
            paths:
            - path: /
          tls:
          - secretName: vaultwarden-tls
            hosts:
            - photos.home.seanho.com
          annotations:
            cert-manager.io/cluster-issuer: le-prod
            nginx.ingress.kubernetes.io/proxy-body-size: 4g
    immich:
      metrics:
        enabled: true
      persistence:
        library:
          existingClaim: photos
    redis:
      enabled: true
