---
apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-values
data:
  values.yaml: |
    env:
      DB_HOSTNAME: immich-db-rw
    postgresql:
      global:
        postgresql:
          auth:
            existingSecret: immich-db-app
    server:
      ingress:
        main:
          enabled: true
          hosts:
          - host: photos.home.seanho.com
            paths:
            - path: /
          tls:
          - secretName: immich-tls
            hosts:
            - photos.home.seanho.com
          annotations:
            cert-manager.io/cluster-issuer: le-prod
            nginx.ingress.kubernetes.io/proxy-body-size: 4g
    immich:
      metrics:
        enabled: true
      persistence:
        library:
          existingClaim: photos
    redis:
      enabled: true
