apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vaultwarden
resources:
- /apps/vaultwarden/
patches:
- path: persistence.yaml
- path: ingress.yaml
- path: smtp.yaml
images:
  # cf helm template for statefulset
- name: vaultwarden 
  # https://hub.docker.com/r/vaultwarden/server
  newTag: 1.32.6-alpine
replicas: 
- name: vaultwarden
  count: 1
