---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux
  path: /infra/configs/
  decryption:
    provider: sops
    secretRef:
      name: flux-sops
  interval: 1h
  prune: true
  wait: true
  dependsOn:
  - name: infra-controllers
