---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - image: eclipse-mosquitto:2.1-alpine
        name: mosquitto
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 1883
          name: mosquitto
        volumeMounts:
        - name: data
          mountPath: /mosquitto/data
        - name: password
          subPath: password.txt
          mountPath: /mosquitto/config/password.txt
        - name: config
          subPath: mosquitto.conf
          mountPath: /mosquitto/config/mosquitto.conf
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mosquitto-data
      - name: password
        secret:
          secretName: mosquitto-password
      - name: config
        configMap:
          name: mosquitto-config
