---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-persistent-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: pods

