# 9iMAp0fKwvca8Kbn
apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-password
stringData:
    password.txt: ENC[AES256_GCM,data:bT5+ZH4iRz8uzfbayaUBSjch/KMlRSiAOHASSJ1FQHw9zPyiv+s/IJRx1Ac3zyx5le2J4XkpZA68DjIkU1HVrBUj2opLh/vyTbNN88eC2M5RP7cJsi4w68sbBdnbEEr84qjyyh5NXugLdqxGMfNijN8kMqZ49g==,iv:slWYBuGOwO6XERsNZhn2NXzxSKYqEQ7pv4kdjjq6NJA=,tag:73Lz49mRhO5BzpNHFEcs9Q==,type:str]
    clear.txt: ENC[AES256_GCM,data:RF6Qtj68hkaYmOLFOuPDB6QR/HH+,iv:vLXXT6jI1iX3Xcz86i820KN5lcdXhEAP7yu3CqngajA=,tag:AcaI43YoMgJxToIFRNVhVQ==,type:str]
sops:
    age:
        - recipient: age1wyr6nlcmwmf6yzlfa9twwspe9cxynhn66rkuwn5rcuy8adeexpys0j67p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMW9mUGZaSjk3azRvTk1C
            RXFQcW1wK0JJNHhBOE1BWStXRTBVbnNhQ2drClk3cmlGT3dIOWNNRnhjbE1hNGN0
            OU5DS3N4SnZtRU5yL3RJOTEwSDdvaTQKLS0tIEhkTWhpNVhHRzVWdDROYTF0Mk5s
            VU5QNDdEeVhPcmlmKzRuNWZRWGZGUG8KsqXcVEHdIpG+xCTj/rXIeBGiJ17OIEgF
            UnKrj+G8Kbguh5VPP7y6G2Apwb41EHflzewXwdZxHMEg0yCmyGs3Yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T01:55:25Z"
    mac: ENC[AES256_GCM,data:Y6IJcUHNqhXi05lX3MS/2WL2lKYryBTjteVQUPf789aLNVTONl/7dWLwcqAdNkX1uhHFA2Rum7CQ/a0q3fIxCGkOhz6EBsWMRGcwzLxE7Uv6KNs3f3mbH6WIu99pjz+dTxIqNfpExY/sSDRGgr+90GWbFhNm5y+Q5uvjXuRD9JY=,iv:x3dxs6maFInV7FRr/u+0mtz05KRgmm/cBBt7eiCq5RI=,tag:wEa7YZvsuc84/qHhw2LakA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
