---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: storage-configs
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux
  path: /storage/configs/
  decryption:
    provider: sops
    secretRef:
      name: flux-sops
  prune: true
  wait: true
  dependsOn:
  - name: storage-controllers
