---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: forgejo
  valuesFrom:
  - kind: ConfigMap
    name: helm-values
