apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin
stringData:
    username: ENC[AES256_GCM,data:qX/KKi+B,iv:CNswOj2chwVHJ9b1XQDGXe7AAlo0lQrUVAo7OZWuYVE=,tag:jxg1XvTtNUMA0jtWkfEUtw==,type:str]
    password: ENC[AES256_GCM,data:G1rEXqZptd3tzB5g8HX7Cw==,iv:1RlD+czxkjcAj8Lgb+l0BOnM395QdD3PT4oNZ8M1ktk=,tag:eD8upaIEGMbZk4/7O5blDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wyr6nlcmwmf6yzlfa9twwspe9cxynhn66rkuwn5rcuy8adeexpys0j67p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqV2Q0T25Sa1dwWWxWTXEw
            blZDdnRhNmRBNHV3Y3JLRmtMWW9Fc3gvcDBFCmorUUF4MGVQZlVVcWF3ckNXU0VT
            bWpPSmt5L0lZb0JWQkZ4dHJOZk1LY1EKLS0tIGR5UmdKT1YwK2E3WUpEOXZjWmFs
            WU5KUDVjYUhaWVdubWpyQmp3V2FNN0kK+wf1m/hzl4eO6JEFtHWJ+1h9+lj2nz9D
            lsyZ67GtAr4ftt0l7ctlSDsGr43ESKNXEoej87ktASCSoZ0QOjAi3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-05T01:20:46Z"
    mac: ENC[AES256_GCM,data:+Ry4HOQxYM9CcdGdygvtmq52ATIMZhDPQ08fVVaGNr4FHQ9e6IpSAL2GCo1f/MzlNvh99vGgtNUlMyP2brgMk9SLGz223OkrPGnBzhIsozaz2/BYDPWOQXi2xSzpkBSORcZvw+tFLS+OuQ49STgcjilrxAdl39XYeXSbr7wG1hI=,iv:HNQDWPA1r3Z3G9FNUIh6D7XxGtGGlimQ8os9W8gsU6c=,tag:q2nI5drPovhp08vLAvG5dw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-db-pw
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:pM1u+dY=,iv:52KS4K3UwlWLTNXaYdB4pzQLIhkubYDFqygNu53jLRw=,tag:JJntr+N9ZerSBy2sIbhOHQ==,type:str]
    password: ENC[AES256_GCM,data:TmOrj9qSnMI1KDcO242Ayer5PoBllWSPSDHv,iv:v9VU22FYr3QVjUmQJceOjYO0I/g/tUvxKJrOl4Tt+ac=,tag:3I5RpFqh7fB3NPWR1+2iWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wyr6nlcmwmf6yzlfa9twwspe9cxynhn66rkuwn5rcuy8adeexpys0j67p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqV2Q0T25Sa1dwWWxWTXEw
            blZDdnRhNmRBNHV3Y3JLRmtMWW9Fc3gvcDBFCmorUUF4MGVQZlVVcWF3ckNXU0VT
            bWpPSmt5L0lZb0JWQkZ4dHJOZk1LY1EKLS0tIGR5UmdKT1YwK2E3WUpEOXZjWmFs
            WU5KUDVjYUhaWVdubWpyQmp3V2FNN0kK+wf1m/hzl4eO6JEFtHWJ+1h9+lj2nz9D
            lsyZ67GtAr4ftt0l7ctlSDsGr43ESKNXEoej87ktASCSoZ0QOjAi3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-05T01:20:46Z"
    mac: ENC[AES256_GCM,data:+Ry4HOQxYM9CcdGdygvtmq52ATIMZhDPQ08fVVaGNr4FHQ9e6IpSAL2GCo1f/MzlNvh99vGgtNUlMyP2brgMk9SLGz223OkrPGnBzhIsozaz2/BYDPWOQXi2xSzpkBSORcZvw+tFLS+OuQ49STgcjilrxAdl39XYeXSbr7wG1hI=,iv:HNQDWPA1r3Z3G9FNUIh6D7XxGtGGlimQ8os9W8gsU6c=,tag:q2nI5drPovhp08vLAvG5dw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
---
apiVersion: v1
kind: Secret
metadata:
    name: values-db
stringData:
    values.yaml: ENC[AES256_GCM,data:9QJoNn6C7sXWzXb7xyPJxzpKpkCcV5AEYBgSelOdm8F7vHrXvIxxWoT0gaUbtXJIwwRhuOfJKbCVnsYLN2MWORvufDFN5pFvSTGGjU39E6JV+hkIpBq7hhvMHBNZGKjoPbHZj9kDNwvdSGtYrIgVj+SmiByqAoSYl4A624BrGoRz0TU9CAfowBQpCPULBjn/LAPSUGPUUFMaxmwsLphNdzPu/VRzpA==,iv:GRwmtfRqqlCMpjwcu3G7/3nm3K85r8G/J1UcX/5cfEo=,tag:hnLYQvieOZcZHsi8JYJh0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wyr6nlcmwmf6yzlfa9twwspe9cxynhn66rkuwn5rcuy8adeexpys0j67p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqV2Q0T25Sa1dwWWxWTXEw
            blZDdnRhNmRBNHV3Y3JLRmtMWW9Fc3gvcDBFCmorUUF4MGVQZlVVcWF3ckNXU0VT
            bWpPSmt5L0lZb0JWQkZ4dHJOZk1LY1EKLS0tIGR5UmdKT1YwK2E3WUpEOXZjWmFs
            WU5KUDVjYUhaWVdubWpyQmp3V2FNN0kK+wf1m/hzl4eO6JEFtHWJ+1h9+lj2nz9D
            lsyZ67GtAr4ftt0l7ctlSDsGr43ESKNXEoej87ktASCSoZ0QOjAi3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-05T01:20:46Z"
    mac: ENC[AES256_GCM,data:+Ry4HOQxYM9CcdGdygvtmq52ATIMZhDPQ08fVVaGNr4FHQ9e6IpSAL2GCo1f/MzlNvh99vGgtNUlMyP2brgMk9SLGz223OkrPGnBzhIsozaz2/BYDPWOQXi2xSzpkBSORcZvw+tFLS+OuQ49STgcjilrxAdl39XYeXSbr7wG1hI=,iv:HNQDWPA1r3Z3G9FNUIh6D7XxGtGGlimQ8os9W8gsU6c=,tag:q2nI5drPovhp08vLAvG5dw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
