# https://code.forgejo.org/forgejo-helm/forgejo-helm/releases
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: forgejo
spec:
  interval: 24h
  url: oci://code.forgejo.org/forgejo-helm/forgejo
  ref:
    tag: 11.0.1
