---
apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-values
data:
  values.yaml: |
    replicaCount: 2
    persistence:
      size: 20Gi
      storageClass: shared-ssd
      accessModes: 
      - ReadWriteMany
    postgresql:
      enabled: false
    gitea:
      admin:
        existingSecret: forgejo-admin
      config:
        APP_NAME: "Anchorlytics Code"
        server:
          PPROF_ENABLED: true
        "cron.GIT_GC_REPOS": 
          ENABLED: false
        actions:
          ENABLED: true
        database:
          DB_TYPE: postgres
          HOST: forgejo-db:5432
          NAME: forgejo
          USER: forgejo
          PASSWD: 
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
    ingress:
      enabled: true
      hosts:
      - host: code.home.seanho.com
        paths:
        - path: /
          pathType: Prefix
      tls:
      - secretName: forgejo-tls
        hosts:
        - code.home.seanho.com
      annotations:
        cert-manager.io/cluster-issuer: le-prod
