---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux
  path: ./clusters/home/apps/
  decryption:
    provider: sops
    secretRef:
      name: flux-sops
  interval: 10m0s
  prune: true
