# https://github.com/grafana/loki/tree/main/production/helm/loki
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 10m
  chart:
    spec:
      interval: 2h
      sourceRef:
        kind: HelmRepository
        name: grafana
      chart: loki
      version: 6.28.0
  valuesFrom:
  - kind: ConfigMap
    name: helm-values
