# https://github.com/cloudnative-pg/charts/tree/main/charts/cloudnative-pg
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
spec:
  interval: 10m
  chart:
    spec:
      interval: 2h
      sourceRef:
        kind: HelmRepository
        name: cnpg
      chart: cloudnative-pg
      version: "0.23.0"
  valuesFrom:
  - kind: ConfigMap
    name: helm-values

