# https://github.com/cloudnative-pg/cloudnative-pg/
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg-system
resources:
- src.yaml
- helm.yaml
- values.yaml
images:
- name: cloudnative-pg
  newTag: 1.25.0

