# https://github.com/cloudnative-pg/cloudnative-pg/
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg-system
resources:
- ns.yaml
- src.yaml
- helm.yaml
- values.yaml
- https://github.com/cloudnative-pg/postgres-containers/raw/refs/heads/main/Debian/ClusterImageCatalog-bookworm.yaml
images:
- name: cloudnative-pg
  newTag: 1.25.0

