---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nzbget-conf
data:
  values.yaml: |
    nzbget:
      config:
        DestDir: /usenet
        InterDir: /usenet/incomplete
        TempDir: /dev/shm
        NzbDir: "${MainDir}/nzb"
        QueueDir: "${MainDir}/queue"
        ScriptDir: "${MainDir}/scripts"
        WebDir: "${AppDir}/webui"
        ConfigTemplate: "${AppDir}/webui/nzbget.conf.template"
        CertStore: "${AppDir}/cacert.pem"
        CertCheck: "yes"

        Category1.Name: movies
        Category2.Name: tv
        Category3.Name: music

        FormAuth: "yes"
        NzbDirInterval: 300
        FlushQueue: "no"
        ContinuePartial: no
        ArticleCache: 500
        DirectWrite: "no"
        WriteBuffer: 1024
        PostStrategy: aggressive
        NzbCleanupDisk: "no"
        KeepHistory: 14

        ArticleTimeout: 60
        ArticleRetries: 6
        ArticleInterval: 60
        UrlRetries: 6
        UrlInterval: 30

        ParBuffer: 500
        DirectRename: "yes"
        DirectUnpack: "yes"
        UnrarCmd: unrar7

        DetailTarget: Screen
        DebugTarget: Screen

