# https://github.com/anchorlytics/charts/tree/main/nzbget
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nzbget
spec:
  interval: 1h
  chart:
    spec:
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: anchorlytics
      chart: nzbget
      version: "0.2.6"
  valuesFrom:
  - kind: ConfigMap
    name: helm-values
  - kind: ConfigMap
    name: nzbget-conf
  - kind: Secret
    name: nzbget-conf
