# https://github.com/anchorlytics/charts/tree/main/nzbget
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nzbget
spec:
  interval: 10m
  chart:
    spec:
      interval: 10m
      sourceRef:
        kind: HelmRepository
        name: anchorlytics
      chart: nzbget
      version: "0.2.2"
  valuesFrom:
  - kind: ConfigMap
    name: helm-values
