# InterDir: in-progress and unpacks
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-cache
  labels:
    app.kubernetes.io/instance: nzbget
    app.kubernetes.io/name: nzbget
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2T
  storageClassName: shared-hdd

