---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  labels:
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: nzbget
    app.kubernetes.io/name: nzbget
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200G
  storageClassName: shared-ssd

