---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget
  labels:
    app.kubernetes.io/instance: nzbget
    app.kubernetes.io/name: nzbget
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10G
  storageClassName: shared-ssd

