apiVersion: v1
kind: Secret
metadata:
    name: config-secret
stringData:
    nzbget.conf: ENC[AES256_GCM,data:tI+kJIQCIM/wIsbhnYla/ugv61ZyzVFBauu844zPe51LTTaI5poX/PcDCPGqMyCrYtcvRutCf/CYs/fd4cvmqNNAQVJfpK7pECnavEha5OiWBMqrxEAoeL7QzWvSCqfpQW9UA/GER+id3bnAK/CyiI0nSTjqIqlIeCgx4VcV/iQSSA6BQ3c0kcB5RKGhWZFbl4nuw+ZwTJ7ZdMTT2PmxuKGSegSDzRc+0qsYghd/f9g74Q4DI/pS78RNBHyWry5LJ4FtYRCtU80uMKHG7nqQSvY2WDJDrxpeS0Vso0jTv14BiB5PvzugSEPYOWmmlieyqiAt3Kql7uKMO/obqQUejcBwZqoHVeRvSNosl9H9/L4OiL4eI8JP/MW8zSPU50I=,iv:zc5z1UqTO1+beF4rpmLrRWPbMMJmFWIyuiIoyiSACPI=,tag:3mBXmMmet/v2a/wqCcIopg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wyr6nlcmwmf6yzlfa9twwspe9cxynhn66rkuwn5rcuy8adeexpys0j67p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SGluVVNOK2lkQk45aEsr
            STZvdm5QK2hTYkptZU12WVRtMGVmZUxGNGtNCnJFdlRjQm04SW0xeE5iSURiYy9z
            RS9mL29MNnlDaDFPYlZtT0xGRWdTSWsKLS0tIG40UG1adjhSNTl3TDJLNXJJa1Jy
            ZXNZbjRHdHNmWm1lY29TRldvcUdweWsKSG7TJZ2Rp4Sk8b/Pp4zaFbOnLOtFjv1h
            8qsb1Rz9XC9VuHDTKrthCfpOdTueELQ54jgxSzacRDvSsuxAx6yezQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-06T09:52:35Z"
    mac: ENC[AES256_GCM,data:jMupEDMNJGfo735luhQXoWTpTxztuuuB7UKkOPFcTAJog7SVFrEVDIcbgXV/qMB7EpAwl63pmbOZM3N5fmGUuoNIRVh6zjhoNxrZsRBr9qY+0t+rIT/LZxAQ1VlmdzTRI0FvtnCh7XMRvVf885CjzjcGrDxVK0mdiW5D40xpTgA=,iv:vyszT2xP8QHswp30Q8sJpeUvUminQlCrQ3cvphri1Qo=,tag:sXF1lhEWy0b2c2IQjrh8NQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
