apiVersion: v1
kind: Secret
metadata:
    name: nzbget-pw
stringData:
    NZBGET_USER: ENC[AES256_GCM,data:DNvCdbOW,iv:+nCRsx6tMiJiV7VfcajVVIkWx2AenIbMOBCaZ7JfYGI=,tag:38otGImY2D3Nn57Ij2n52Q==,type:str]
    NZBGET_PASS: ENC[AES256_GCM,data:9JxpSjzoB2/6wb/lViDFHQj8no8=,iv:9q1BuHW9luREbJVSb/MXHdfeEzIgLaaXrSuhkJAC1ng=,tag:r4khMTTeo1n/JgDXVrFUaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wyr6nlcmwmf6yzlfa9twwspe9cxynhn66rkuwn5rcuy8adeexpys0j67p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SGluVVNOK2lkQk45aEsr
            STZvdm5QK2hTYkptZU12WVRtMGVmZUxGNGtNCnJFdlRjQm04SW0xeE5iSURiYy9z
            RS9mL29MNnlDaDFPYlZtT0xGRWdTSWsKLS0tIG40UG1adjhSNTl3TDJLNXJJa1Jy
            ZXNZbjRHdHNmWm1lY29TRldvcUdweWsKSG7TJZ2Rp4Sk8b/Pp4zaFbOnLOtFjv1h
            8qsb1Rz9XC9VuHDTKrthCfpOdTueELQ54jgxSzacRDvSsuxAx6yezQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-06T20:30:42Z"
    mac: ENC[AES256_GCM,data:1miJvCL4dtEGlpcIW5dpZWJT/KtCxbE3ruSLGTFLwoZwISNl31dC2/OyqSH8Fkd7X0cvUXICpDJBQ7o0fTcuETlGYk0M63Xj+F91WfZA8RQfn02K4d4Z/EOoPE26Iv9skESckIFyKUR5r4um8RYxk5pJOk6JxXuOscqIvMVx+p8=,iv:HR9SkRfTi76gVYSyGNQX2oqz4R+O6+6TU29LPK3HM/I=,tag:ZOd1e+bqaMwcrh/iaRzbkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
---
apiVersion: v1
kind: Secret
metadata:
    name: nzbget-conf
stringData:
    values.yaml: ENC[AES256_GCM,data:IodqTwA2HwQOZMN/lUzR7rf5bsOJihKR5oI/S1nlcBMYnRc8vFL24ksKcVzrTqWMsKlFgaToOMiX+zs9Vr80SlIntju3D4stBSnazD1jc9AGxmZkQjodDdP682VbEsQR1SyzYsvF6VnWQuxF3PU9zZ3vUgGPVhLR8A6kIdWF2UsV4Sq5RAF4SMLMLRlCzdAYt6EDJ+lbAnW9KdYkgXSVd18TMYetGzPP3HC8niiCqgEQ7o8vaLlDSiH+RmInK/1TE6UVTXG7+srswM8zOFYQT/JRiialEO9IMKorWs0iLjm0LrTJW06ArLmq18qN1Yan0kAS3JhclkK7z+txKRAeCo8mHX+dOiD76WBPa7HuRUEKuY+36ErROLZBD7STjVMAotVzEoskkN8RQ7+D79HCO2FQ2sGuSeqFFTPB6smbjwN9u6pmXf4PILhyi5Ii4tY0tKs37Pvox3YHaOr7V8yUh5ytovgMOlQs9f4yN6gKPi1ojRk4/WdXdspNdqrYRx+0pYRGWJeEZiCZoaWt4+9umO1sDH8=,iv:s6mWtxlfDUQYP2nKfO1zhIi1p7974/bFijHZ8Na7AcI=,tag:PFBXLpQyiyfJC2NiQ83krw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wyr6nlcmwmf6yzlfa9twwspe9cxynhn66rkuwn5rcuy8adeexpys0j67p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SGluVVNOK2lkQk45aEsr
            STZvdm5QK2hTYkptZU12WVRtMGVmZUxGNGtNCnJFdlRjQm04SW0xeE5iSURiYy9z
            RS9mL29MNnlDaDFPYlZtT0xGRWdTSWsKLS0tIG40UG1adjhSNTl3TDJLNXJJa1Jy
            ZXNZbjRHdHNmWm1lY29TRldvcUdweWsKSG7TJZ2Rp4Sk8b/Pp4zaFbOnLOtFjv1h
            8qsb1Rz9XC9VuHDTKrthCfpOdTueELQ54jgxSzacRDvSsuxAx6yezQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-06T20:30:42Z"
    mac: ENC[AES256_GCM,data:1miJvCL4dtEGlpcIW5dpZWJT/KtCxbE3ruSLGTFLwoZwISNl31dC2/OyqSH8Fkd7X0cvUXICpDJBQ7o0fTcuETlGYk0M63Xj+F91WfZA8RQfn02K4d4Z/EOoPE26Iv9skESckIFyKUR5r4um8RYxk5pJOk6JxXuOscqIvMVx+p8=,iv:HR9SkRfTi76gVYSyGNQX2oqz4R+O6+6TU29LPK3HM/I=,tag:ZOd1e+bqaMwcrh/iaRzbkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
