# https://github.com/nzbgetcom/nzbget/blob/develop/nzbget.conf
# https://trash-guides.info/Downloaders/NZBGet/Basic-Setup/
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-values
data:
  values.yaml: |
    volumes:
    - name: appdata
      persistentVolumeClaim:
        claimName: nzbget
    - name: cache
      emptyDir:
        sizeLimit: 20Gi
        medium: Memory
    - name: usenset
      persistentVolumeClaim:
        claimName: usenet
    volumeMounts:
    - name: cache
      mountPath: /cache
    - name: usenet
      mountPath: /usenet
    ingress:
      enabled: true
      host: nzb.home.seanho.com
      annotations:
        cert-manager.io/cluster-issuer: le-prod
        nginx.ingress.kubernetes.io/proxy-body-size: 1m
