---
apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-values
data:
  values.yaml: |
    ingress:
      enabled: true
      hostname: nzb.home.seanho.com
      annotations:
        cert-manager.io/cluster-issuer: le-prod
        nginx.ingress.kubernetes.io/proxy-body-size: 1m
