# https://github.com/dani-garcia/vaultwarden/releases
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- vaultwarden/
images:
- name: vaultwarden/server
  newTag: 1.32.7
