# shared with jellyfin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10T
  storageClassName: shared-hdd
