# https://github.com/cert-manager/cert-manager/releases
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 20m
  chart:
    spec:
      interval: 2h
      sourceRef:
        kind: HelmRepository
        name: jetstack
      chart: cert-manager
      version: "1.17.1"
  valuesFrom:
  - kind: ConfigMap
    name: helm-values

