---
apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-values
data:
  values.yaml: |
    installCRDs: true
    prometheus:
      servicemonitor:
        enabled: true
    ingressShim:
      defaultIssuerName: le-prod
      defaultIssuerKind: ClusterIssuer
    dns01RecursiveNameserversOnly: true
    dns01RecursiveNameservers: "1.1.1.1:53"
