---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nfd
resources:
- "https://github.com/intel/intel-device-plugins-for-kubernetes/raw/refs/heads/main/deployments/nfd/overlays/node-feature-rules/node-feature-rules.yaml"
