---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: nfd
spec:
  interval: 24h
  url: "oci://registry.k8s.io/nfd/charts/node-feature-discovery"
  ref:
   semver: "^0.2.1"

